name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install  # Adjust to your package manager and dependencies if needed

    - name: Build the site
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        sed -i 's/\${API_KEY}/'${API_KEY}'/g' index.html  # Replace placeholder with the actual key
        npm run build  # Adjust to your build script

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Adjust to your build directory
